### ISSUE TITLE
[Moonbeam Challenge]Can't read address value

### ISSUE THREAD

**Issue by albertov19** [jossimunoz/polkadot-hackathon#1]
Hey, I can't read the address1, address2, and addressToken from that address. Could you share the structure of the contract where you stored this variables?

**Comment by jossimunoz** [comment]
Hi, I think there is a problem with the rpc, I try to load the erc20 token and checkContract  from the addresses in remix and it doesn't load


pragma solidity >0.6.99 <0.8.0;


contract checkContact {
    
    string public address1 = "0x7E32A0f28767FF35738023e56454A181B7Ae9A61";
    string public address2  = "0x12Cb274aAD8251C875c0bf6872b67d9983E53fDd";
    string public addressToken  = "0xEaE3fb599Fc925a14B32751e8AEE30d5bBFACe7B";
    
}

**Comment by albertov19** [comment]
Yes currently we are experiencing some issues with the RPC. But there is an issue with your contract. Try to understand what is the problem ;). I mean your addresses are correct but I cannot retrieve them with the automated script because of an issue with you checkContract.

**Comment by albertov19** [comment]
Jossimunoz just checking if you manged to complete the challenge. The RPC issues were fix already.

**Comment by jossimunoz** [comment]
hi @albertov19 I just uploaded a commit with the new address of the contract https://github.com/jossimunoz/polkadot-hackathon/commit/db9fb853cb61928646f8b451159c7eae0986ed97

**Comment by albertov19** [comment]
Hi @jossimunoz,

Your check contract is still in the wrong format. Make sure that you submit these variables as address type and not string. That was the issue from before as well.

Regards.
Alberto

**Comment by jossimunoz** [comment]
yes, the commit that I uploaded has that correction (0x2dafe6BeD5dF9A5D199D78052cd42E5A691916Af) 

`
pragma solidity >0.6.99 <0.8.0;


contract checkContact {
    
    address public address1 = 0x7E32A0f28767FF35738023e56454A181B7Ae9A61;
    address public address2  = 0x12Cb274aAD8251C875c0bf6872b67d9983E53fDd;
    address public addressToken  = 0xEaE3fb599Fc925a14B32751e8AEE30d5bBFACe7B;
    
}`
